# Archivo: docker-compose.yml
version: '3'

services:
  client-app:
    build: ./client-app
    ports:
      - "3000:80"
    environment:
      - VITE_INVENTORY_API_URL=http://localhost:8081/api
      - VITE_ORDER_API_URL=http://localhost:8082/api
      - VITE_NOTIFICATION_API_URL=http://localhost:8083/api
    depends_on:
      - inventory-service
      - order-service
      - notification-service

  restaurant-admin:
    build: ./restaurant-admin
    ports:
      - "3001:80"
    environment:
      - VITE_INVENTORY_API_URL=http://localhost:8081/api
      - VITE_ORDER_API_URL=http://localhost:8082/api
      - VITE_NOTIFICATION_API_URL=http://localhost:8083/api
    depends_on:
      - inventory-service
      - order-service
      - notification-service

  inventory-service:
    build: ./inventory-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - MONGODB_URI=mongodb://mongodb:27017/stadium-inventory
    depends_on:
      - mongodb
    restart: on-failure
    volumes:
      - ./inventory-service:/app
      - /app/node_modules

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=stadium-orders
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - KAFKA_BROKER=kafka:9092
      - INVENTORY_SERVICE_URL=http://inventory-service:8081
    depends_on:
      - postgres
      - kafka
      - inventory-service
    restart: on-failure
    volumes:
      - ./order-service:/app
      - /app/node_modules

  notification-service:
    build: ./notification-service
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - MONGODB_URI=mongodb://mongodb:27017/stadium-notifications
      - KAFKA_BROKER=kafka:9092
      - ORDER_SERVICE_URL=http://order-service:8082
    depends_on:
      - mongodb
      - kafka
      - order-service
    restart: on-failure
    volumes:
      - ./notification-service:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stadium-orders
    volumes:
      - postgres-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka-setup:
    image: confluentinc/cp-kafka:latest
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c "
        echo 'Waiting for Kafka to be ready...' &&
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic order-events --partitions 1 --replication-factor 1 &&
        echo 'Successfully created topics'"

  # Scripts para inicializar datos
  seed-data:
    build: ./inventory-service
    command: node scripts/seed-data.js
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/stadium-inventory
    depends_on:
      - mongodb

volumes:
  mongodb-data:
  postgres-data: