apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: stadium-delivery/notification-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
        env:
        - name: PORT
          value: "8083"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/stadium-notifications"
        - name: KAFKA_BROKER
          value: "kafka:9092"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /api/notifications/health
            port: 8083
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/notifications/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 30