apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "orders"
  PORT: "8082"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  INVENTORY_SERVICE_URL: "http://inventory-service:8081"
